/**
 * @file Audit action constants
 * @description Enumeration of all actions that are recorded in the audit log.
 * Centralising these strings prevents inconsistent action names from appearing
 * in the audit history and makes it easy to query specific action types.
 */

export const AUDIT_ACTION = Object.freeze({
  // Incident lifecycle
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_UPDATED: 'INCIDENT_UPDATED',
  INCIDENT_DELETED: 'INCIDENT_DELETED',
  INCIDENT_STATUS_CHANGED: 'INCIDENT_STATUS_CHANGED',
  INCIDENT_PRIORITY_CHANGED: 'INCIDENT_PRIORITY_CHANGED',
  INCIDENT_ASSIGNED: 'INCIDENT_ASSIGNED',
  INCIDENT_UNASSIGNED: 'INCIDENT_UNASSIGNED',
  INCIDENT_ESCALATED: 'INCIDENT_ESCALATED',

  // Comments
  COMMENT_ADDED: 'COMMENT_ADDED',
  COMMENT_EDITED: 'COMMENT_EDITED',
  COMMENT_DELETED: 'COMMENT_DELETED',

  // Attachments
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',

  // User management
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',

  // Team management
  TEAM_MEMBER_ADDED: 'TEAM_MEMBER_ADDED',
  TEAM_MEMBER_REMOVED: 'TEAM_MEMBER_REMOVED',
});

/** Notification type constants */
export const NOTIFICATION_TYPE = Object.freeze({
  INCIDENT_ASSIGNED: 'INCIDENT_ASSIGNED',
  INCIDENT_UPDATED: 'INCIDENT_UPDATED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  SLA_AT_RISK: 'SLA_AT_RISK',
  SLA_BREACHED: 'SLA_BREACHED',
  INCIDENT_ESCALATED: 'INCIDENT_ESCALATED',
});
