-- =============================================================================
-- Migration: 0001_initial_schema
-- Description: Full initial database schema for the Incident Management Platform
--
-- Conventions used throughout:
--   • All primary keys are UUIDs generated by gen_random_uuid() (pgcrypto).
--   • All table names are snake_case, mapped from Prisma camelCase models.
--   • Every timestamp column is timestamptz (timezone-aware UTC storage).
--   • Soft-deleted rows retain a non-NULL deleted_at.
--   • Audit log tables are APPEND-ONLY — no UPDATE or DELETE is ever issued
--     by application code; this is enforced at the service layer.
--   • Foreign key constraints use explicit names for easier debugging.
--   • Check constraints guard against impossible enum values at the DB level.
-- =============================================================================

-- Enable pgcrypto for gen_random_uuid() (available in Postgres 13+; built-in
-- gen_random_uuid() is available natively in Postgres 14+, but explicit
-- extension call keeps compatibility with 13).
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- ENUMERATIONS
-- Using native Postgres ENUM types gives CHECK-constraint-level correctness
-- with O(1) storage (internally stored as int4) and readable pg_type catalog.
-- =============================================================================

CREATE TYPE "UserRole" AS ENUM (
  'ADMIN',
  'MANAGER',
  'ENGINEER',
  'VIEWER'
);

CREATE TYPE "IncidentStatus" AS ENUM (
  'OPEN',
  'IN_PROGRESS',
  'ON_HOLD',
  'RESOLVED',
  'CLOSED'
);

CREATE TYPE "IncidentPriority" AS ENUM (
  'CRITICAL',
  'HIGH',
  'MEDIUM',
  'LOW'
);

CREATE TYPE "IncidentCategory" AS ENUM (
  'INFRASTRUCTURE',
  'APPLICATION',
  'SECURITY',
  'NETWORK',
  'DATABASE',
  'PERFORMANCE',
  'OTHER'
);

CREATE TYPE "NotificationType" AS ENUM (
  'INCIDENT_ASSIGNED',
  'INCIDENT_UPDATED',
  'INCIDENT_RESOLVED',
  'COMMENT_ADDED',
  'SLA_AT_RISK',
  'SLA_BREACHED',
  'INCIDENT_ESCALATED'
);

CREATE TYPE "AuditAction" AS ENUM (
  'INCIDENT_CREATED',
  'INCIDENT_UPDATED',
  'INCIDENT_DELETED',
  'INCIDENT_RESTORED',
  'STATUS_CHANGED',
  'PRIORITY_CHANGED',
  'ASSIGNED',
  'UNASSIGNED',
  'REASSIGNED',
  'COMMENT_ADDED',
  'COMMENT_EDITED',
  'COMMENT_DELETED',
  'ATTACHMENT_ADDED',
  'ATTACHMENT_DELETED',
  'SLA_BREACHED',
  'SLA_PAUSED',
  'SLA_RESUMED',
  'USER_ROLE_CHANGED',
  'USER_DEACTIVATED',
  'USER_ACTIVATED'
);

-- =============================================================================
-- ORGANIZATIONS
-- =============================================================================

CREATE TABLE "organizations" (
  "id"         UUID        NOT NULL DEFAULT gen_random_uuid(),
  "name"       TEXT        NOT NULL,
  -- slug: URL-safe tenant identifier (lowercase, hyphens).
  -- Used in subdomain routing and API path prefixes.
  "slug"       TEXT        NOT NULL,
  "logo_url"   TEXT,
  "active"     BOOLEAN     NOT NULL DEFAULT TRUE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "organizations_pkey"        PRIMARY KEY ("id"),
  CONSTRAINT "organizations_name_unique" UNIQUE ("name"),
  CONSTRAINT "organizations_slug_unique" UNIQUE ("slug"),
  -- slug must be lowercase, URL-safe (letters, digits, hyphens only)
  CONSTRAINT "organizations_slug_format"
    CHECK ("slug" ~ '^[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]$')
);

-- Slug is queried on every request when resolving tenant context (subdomain lookup)
CREATE INDEX "organizations_slug_idx"   ON "organizations" ("slug");
CREATE INDEX "organizations_active_idx" ON "organizations" ("active");

-- =============================================================================
-- ROLES (reference table for UI labels and future permission expansion)
-- =============================================================================

CREATE TABLE "roles" (
  "id"          UUID        NOT NULL DEFAULT gen_random_uuid(),
  "name"        "UserRole"  NOT NULL,
  "label"       TEXT        NOT NULL,  -- e.g. "Support Engineer"
  "description" TEXT        NOT NULL,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "roles_pkey"        PRIMARY KEY ("id"),
  CONSTRAINT "roles_name_unique" UNIQUE ("name")
);

-- =============================================================================
-- USERS
-- =============================================================================

CREATE TABLE "users" (
  "id"            UUID        NOT NULL DEFAULT gen_random_uuid(),
  "email"         TEXT        NOT NULL,
  -- password_hash: bcrypt output — never store plaintext passwords
  "password_hash" TEXT        NOT NULL,
  "display_name"  TEXT        NOT NULL,
  "avatar_url"    TEXT,
  "role"          "UserRole"  NOT NULL DEFAULT 'ENGINEER',
  -- active = FALSE is a soft-delete; audit logs retain the reference
  "active"        BOOLEAN     NOT NULL DEFAULT TRUE,
  "last_login_at" TIMESTAMPTZ,
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "users_pkey"         PRIMARY KEY ("id"),
  CONSTRAINT "users_email_unique" UNIQUE ("email"),
  -- Basic email format check — prevents obviously malformed data at DB level
  CONSTRAINT "users_email_format" CHECK ("email" ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

-- role: admin panel "filter by role", RBAC checks
CREATE INDEX "users_role_idx"   ON "users" ("role");
-- active: every auth middleware call appends AND active = true
CREATE INDEX "users_active_idx" ON "users" ("active");

-- =============================================================================
-- ORGANIZATION MEMBERS (user ↔ org join table)
-- =============================================================================

CREATE TABLE "organization_members" (
  "user_id"         UUID        NOT NULL,
  "organization_id" UUID        NOT NULL,
  "joined_at"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "org_members_pkey"
    PRIMARY KEY ("user_id", "organization_id"),
  CONSTRAINT "fk_org_members_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_org_members_org"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE
);

-- "Which orgs does this user belong to?" — auth middleware context resolution
CREATE INDEX "org_members_user_id_idx" ON "organization_members" ("user_id");
-- "Who belongs to this org?" — admin user-management page
CREATE INDEX "org_members_org_id_idx"  ON "organization_members" ("organization_id");

-- =============================================================================
-- REFRESH TOKENS
-- =============================================================================

CREATE TABLE "refresh_tokens" (
  "id"         UUID        NOT NULL DEFAULT gen_random_uuid(),
  "user_id"    UUID        NOT NULL,
  -- jti matches the `jti` JWT claim; used for replay detection and revocation
  "jti"        TEXT        NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "revoked"    BOOLEAN     NOT NULL DEFAULT FALSE,
  "user_agent" TEXT,
  "ip_address" TEXT,

  CONSTRAINT "refresh_tokens_pkey"       PRIMARY KEY ("id"),
  CONSTRAINT "refresh_tokens_jti_unique" UNIQUE ("jti"),
  CONSTRAINT "fk_refresh_tokens_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- "Revoke all tokens for this user" on password change / forced logout
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens" ("user_id");
-- Token verification: O(log n) lookup by jti on every /auth/refresh call
CREATE INDEX "refresh_tokens_jti_idx"     ON "refresh_tokens" ("jti");

-- =============================================================================
-- SESSIONS
-- =============================================================================

CREATE TABLE "sessions" (
  "id"           UUID        NOT NULL DEFAULT gen_random_uuid(),
  "user_id"      UUID        NOT NULL,
  -- jti links to the refresh_token that opened this session
  "jti"          TEXT        NOT NULL,
  "expires_at"   TIMESTAMPTZ NOT NULL,
  "created_at"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "last_seen_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "user_agent"   TEXT,
  "ip_address"   TEXT,
  "active"       BOOLEAN     NOT NULL DEFAULT TRUE,

  CONSTRAINT "sessions_pkey"       PRIMARY KEY ("id"),
  CONSTRAINT "sessions_jti_unique" UNIQUE ("jti"),
  CONSTRAINT "fk_sessions_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- "Show all active sessions for this user" — security settings page
CREATE INDEX "sessions_user_id_active_idx" ON "sessions" ("user_id", "active");

-- =============================================================================
-- TEAMS
-- =============================================================================

CREATE TABLE "teams" (
  "id"              UUID        NOT NULL DEFAULT gen_random_uuid(),
  "organization_id" UUID        NOT NULL,
  "name"            TEXT        NOT NULL,
  "description"     TEXT,
  "created_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "teams_pkey"        PRIMARY KEY ("id"),
  -- Team name must be unique within an organization, not globally
  CONSTRAINT "teams_org_name_unique" UNIQUE ("organization_id", "name"),
  CONSTRAINT "fk_teams_org"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE
);

-- Org-scoped team listing — team management page
CREATE INDEX "teams_org_id_idx" ON "teams" ("organization_id");

-- =============================================================================
-- TEAM MEMBERS
-- =============================================================================

CREATE TABLE "team_members" (
  "user_id"   UUID        NOT NULL,
  "team_id"   UUID        NOT NULL,
  -- 'MEMBER' | 'LEAD' — kept as text rather than enum to allow future values
  "role"      TEXT        NOT NULL DEFAULT 'MEMBER',
  "joined_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "team_members_pkey"      PRIMARY KEY ("user_id", "team_id"),
  CONSTRAINT "team_members_role_check" CHECK ("role" IN ('MEMBER', 'LEAD')),
  CONSTRAINT "fk_team_members_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_team_members_team"
    FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE
);

-- All members of a team — team detail page roster
CREATE INDEX "team_members_team_id_idx" ON "team_members" ("team_id");

-- =============================================================================
-- SLA POLICIES
-- =============================================================================

CREATE TABLE "sla_policies" (
  "id"                  UUID              NOT NULL DEFAULT gen_random_uuid(),
  "organization_id"     UUID              NOT NULL,
  "name"                TEXT              NOT NULL,
  "priority"            "IncidentPriority" NOT NULL,
  -- response_minutes: time from creation to first response
  "response_minutes"    INTEGER           NOT NULL,
  -- resolution_minutes: time from creation to full resolution
  "resolution_minutes"  INTEGER           NOT NULL,
  "active"              BOOLEAN           NOT NULL DEFAULT TRUE,
  "created_at"          TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  "updated_at"          TIMESTAMPTZ       NOT NULL DEFAULT NOW(),

  CONSTRAINT "sla_policies_pkey"          PRIMARY KEY ("id"),
  -- One SLA policy per priority per org — enforced here, not just in app code
  CONSTRAINT "sla_policies_org_priority_unique" UNIQUE ("organization_id", "priority"),
  CONSTRAINT "sla_policies_response_positive"
    CHECK ("response_minutes" > 0),
  CONSTRAINT "sla_policies_resolution_positive"
    CHECK ("resolution_minutes" > 0),
  -- Resolution must always be at least as long as response time
  CONSTRAINT "sla_policies_resolution_gte_response"
    CHECK ("resolution_minutes" >= "response_minutes"),
  CONSTRAINT "fk_sla_policies_org"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE
);

-- Incident creation query: find the right SLA policy for this org + priority
CREATE INDEX "sla_policies_org_priority_idx" ON "sla_policies" ("organization_id", "priority");
CREATE INDEX "sla_policies_active_idx"       ON "sla_policies" ("active");

-- =============================================================================
-- INCIDENTS
-- =============================================================================

-- Per-organization incident number sequence.
-- We use a single global sequence and store the number per incident row.
-- The unique constraint (organization_id, incident_number) enforces per-org
-- uniqueness. The sequence itself is org-agnostic for simplicity; numbers may
-- not be perfectly sequential per org but will always be unique and ascending.
-- For strict per-org sequential numbers, a trigger-based approach would be
-- needed — acceptable tradeoff for this schema version.
CREATE SEQUENCE "incident_number_seq" START 1 INCREMENT 1;

CREATE TABLE "incidents" (
  "id"               UUID               NOT NULL DEFAULT gen_random_uuid(),
  -- incident_number: human-readable reference, e.g. INC-0001
  -- DEFAULT pulls from shared sequence; application code can also supply it
  "incident_number"  INTEGER            NOT NULL DEFAULT nextval('incident_number_seq'),
  "title"            TEXT               NOT NULL,
  "description"      TEXT               NOT NULL,
  "status"           "IncidentStatus"   NOT NULL DEFAULT 'OPEN',
  "priority"         "IncidentPriority" NOT NULL DEFAULT 'MEDIUM',
  "category"         "IncidentCategory" NOT NULL DEFAULT 'OTHER',

  -- Tenant + party relationships
  "organization_id"  UUID               NOT NULL,
  "reporter_id"      UUID               NOT NULL,
  "assignee_id"      UUID,
  "team_id"          UUID,
  "sla_id"           UUID,

  -- SLA tracking
  "sla_breach_at"      TIMESTAMPTZ,
  "sla_breached"       BOOLEAN     NOT NULL DEFAULT FALSE,
  -- sla_hold_started_at: set when status transitions to ON_HOLD
  "sla_hold_started_at" TIMESTAMPTZ,
  -- sla_hold_minutes: accumulated pause time added back to sla_breach_at
  "sla_hold_minutes"   INTEGER     NOT NULL DEFAULT 0,
  -- resolution_time: minutes from creation to resolution (null until resolved)
  "resolution_time"    INTEGER,

  -- Lifecycle timestamps
  "assigned_at" TIMESTAMPTZ,
  "resolved_at" TIMESTAMPTZ,
  "closed_at"   TIMESTAMPTZ,
  "due_at"      TIMESTAMPTZ,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Soft-delete: application sets this instead of DELETE
  "deleted_at"  TIMESTAMPTZ,

  CONSTRAINT "incidents_pkey" PRIMARY KEY ("id"),
  -- Human lookup: "INC-0042 in org X" — also prevents duplicate numbers per org
  CONSTRAINT "incidents_org_number_unique" UNIQUE ("organization_id", "incident_number"),

  -- Semantic integrity: closed timestamp implies prior resolution
  CONSTRAINT "incidents_closed_after_resolved"
    CHECK (
      "closed_at" IS NULL
      OR "resolved_at" IS NULL
      OR "closed_at" >= "resolved_at"
    ),
  -- resolved_at must not predate creation
  CONSTRAINT "incidents_resolved_after_created"
    CHECK ("resolved_at" IS NULL OR "resolved_at" >= "created_at"),
  -- resolution_time must be non-negative
  CONSTRAINT "incidents_resolution_time_positive"
    CHECK ("resolution_time" IS NULL OR "resolution_time" >= 0),
  -- sla_hold_minutes must be non-negative
  CONSTRAINT "incidents_hold_minutes_positive"
    CHECK ("sla_hold_minutes" >= 0),

  CONSTRAINT "fk_incidents_org"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id"),
  CONSTRAINT "fk_incidents_reporter"
    FOREIGN KEY ("reporter_id") REFERENCES "users"("id"),
  CONSTRAINT "fk_incidents_assignee"
    FOREIGN KEY ("assignee_id") REFERENCES "users"("id"),
  CONSTRAINT "fk_incidents_team"
    FOREIGN KEY ("team_id") REFERENCES "teams"("id"),
  CONSTRAINT "fk_incidents_sla"
    FOREIGN KEY ("sla_id") REFERENCES "sla_policies"("id")
);

-- status: "all open incidents" list — single column filter
CREATE INDEX "incidents_status_idx"           ON "incidents" ("status");
-- priority: "critical incidents" alert list
CREATE INDEX "incidents_priority_idx"         ON "incidents" ("priority");
-- status + priority: most common dashboard composite — "OPEN CRITICAL"
CREATE INDEX "incidents_status_priority_idx"  ON "incidents" ("status", "priority");
-- org + status: every tenant-scoped query; prevents cross-tenant full scans
CREATE INDEX "incidents_org_status_idx"       ON "incidents" ("organization_id", "status");
-- org + status + priority: tenant-scoped dashboard combo
CREATE INDEX "incidents_org_status_prio_idx"  ON "incidents" ("organization_id", "status", "priority");
-- assignee: "my incidents" workload page
CREATE INDEX "incidents_assignee_idx"         ON "incidents" ("assignee_id");
-- org + assignee + status: workload query for one engineer in one tenant, excluding closed
CREATE INDEX "incidents_org_assignee_status_idx" ON "incidents" ("organization_id", "assignee_id", "status");
-- team: team dashboard
CREATE INDEX "incidents_team_idx"             ON "incidents" ("team_id");
-- reporter: "incidents I reported" filter
CREATE INDEX "incidents_reporter_idx"         ON "incidents" ("reporter_id");
-- sla_breach_at: SLA monitor cron job — WHERE sla_breach_at <= NOW()
CREATE INDEX "incidents_sla_breach_at_idx"    ON "incidents" ("sla_breach_at");
-- sla_breached + status: dashboard breach count badge
CREATE INDEX "incidents_sla_breached_status_idx" ON "incidents" ("sla_breached", "status");
-- created_at: trend charts, time-range queries, default sort
CREATE INDEX "incidents_created_at_idx"       ON "incidents" ("created_at");
-- updated_at: "recently updated" activity feed
CREATE INDEX "incidents_updated_at_idx"       ON "incidents" ("updated_at");
-- deleted_at: WHERE deleted_at IS NULL appears on virtually every list query
CREATE INDEX "incidents_deleted_at_idx"       ON "incidents" ("deleted_at");

-- =============================================================================
-- INCIDENT ASSIGNMENTS (assignment history)
-- =============================================================================

CREATE TABLE "incident_assignments" (
  "id"             UUID        NOT NULL DEFAULT gen_random_uuid(),
  "incident_id"    UUID        NOT NULL,
  "assignee_id"    UUID        NOT NULL,
  "assigned_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- unassigned_at: NULL means this is the current assignment
  "unassigned_at"  TIMESTAMPTZ,
  "assigned_by_id" UUID        NOT NULL,

  CONSTRAINT "incident_assignments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "fk_ia_incident"
    FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_ia_assignee"
    FOREIGN KEY ("assignee_id") REFERENCES "users"("id"),
  CONSTRAINT "fk_ia_assigned_by"
    FOREIGN KEY ("assigned_by_id") REFERENCES "users"("id")
);

-- Assignment timeline per incident — main read pattern for this table
CREATE INDEX "ia_incident_assigned_at_idx" ON "incident_assignments" ("incident_id", "assigned_at");
-- Historical workload per engineer
CREATE INDEX "ia_assignee_assigned_at_idx" ON "incident_assignments" ("assignee_id", "assigned_at");

-- =============================================================================
-- INCIDENT COMMENTS
-- =============================================================================

CREATE TABLE "incident_comments" (
  "id"          UUID        NOT NULL DEFAULT gen_random_uuid(),
  "incident_id" UUID        NOT NULL,
  "author_id"   UUID        NOT NULL,
  "body"        TEXT        NOT NULL,
  -- is_internal: internal notes hidden from VIEWER role (enforced at repo layer)
  "is_internal" BOOLEAN     NOT NULL DEFAULT FALSE,
  "edited_at"   TIMESTAMPTZ,
  -- Soft-delete preserves comment history in the audit trail
  "deleted_at"  TIMESTAMPTZ,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "incident_comments_pkey" PRIMARY KEY ("id"),
  -- A comment body must not be empty
  CONSTRAINT "incident_comments_body_nonempty" CHECK (length(trim("body")) > 0),
  CONSTRAINT "fk_comments_incident"
    FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_comments_author"
    FOREIGN KEY ("author_id") REFERENCES "users"("id")
);

-- Comment thread per incident — paginated list, newest first
CREATE INDEX "comments_incident_created_idx" ON "incident_comments" ("incident_id", "created_at");
CREATE INDEX "comments_author_idx"           ON "incident_comments" ("author_id");

-- =============================================================================
-- INCIDENT ATTACHMENTS
-- =============================================================================

CREATE TABLE "incident_attachments" (
  "id"            UUID        NOT NULL DEFAULT gen_random_uuid(),
  "incident_id"   UUID        NOT NULL,
  "uploaded_by_id" UUID       NOT NULL,
  "filename"      TEXT        NOT NULL,           -- Original name shown in UI
  "storage_path"  TEXT        NOT NULL,           -- Disk path or S3 object key
  "mime_type"     TEXT        NOT NULL,
  "size"          INTEGER     NOT NULL,           -- Bytes
  "deleted_at"    TIMESTAMPTZ,
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "incident_attachments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "attachments_size_positive" CHECK ("size" > 0),
  CONSTRAINT "fk_attachments_incident"
    FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_attachments_uploader"
    FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id")
);

-- Attachment list on incident detail page
CREATE INDEX "attachments_incident_idx" ON "incident_attachments" ("incident_id");

-- =============================================================================
-- INCIDENT ACTIVITY (human-readable timeline feed)
-- =============================================================================

CREATE TABLE "incident_activities" (
  "id"          UUID        NOT NULL DEFAULT gen_random_uuid(),
  "incident_id" UUID        NOT NULL,
  -- actor_id is NULL for system-generated entries (e.g., SLA auto-breach)
  "actor_id"    UUID,
  -- message: human-readable text, e.g. "Alice reassigned this to Bob"
  "message"     TEXT        NOT NULL,
  -- event_type: machine-readable identifier for icon/badge rendering in the UI
  "event_type"  TEXT        NOT NULL,
  "metadata"    JSONB,
  "created_at"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT "incident_activities_pkey" PRIMARY KEY ("id"),
  -- The incident must exist; cascade on hard-delete (soft-delete path preferred)
  CONSTRAINT "fk_activities_incident"
    FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE CASCADE
);

-- Timeline per incident — paginated, ordered by created_at ascending
CREATE INDEX "activities_incident_created_idx" ON "incident_activities" ("incident_id", "created_at");

-- =============================================================================
-- INCIDENT AUDIT LOGS (immutable compliance log)
-- =============================================================================

CREATE TABLE "incident_audit_logs" (
  "id"          UUID          NOT NULL DEFAULT gen_random_uuid(),
  -- incident_id is nullable: user role changes are global, not tied to an incident
  "incident_id" UUID,
  "actor_id"    UUID          NOT NULL,
  "action"      "AuditAction" NOT NULL,
  -- field_name: set for INCIDENT_UPDATED to name the changed field
  "field_name"  TEXT,
  -- old_value / new_value: stored as JSON strings (supports complex types)
  "old_value"   TEXT,
  "new_value"   TEXT,
  "metadata"    JSONB,
  "created_at"  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

  CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"),
  -- ON DELETE SET NULL: if an incident is hard-deleted, logs survive with null FK
  CONSTRAINT "fk_audit_incident"
    FOREIGN KEY ("incident_id") REFERENCES "incidents"("id") ON DELETE SET NULL,
  CONSTRAINT "fk_audit_actor"
    FOREIGN KEY ("actor_id") REFERENCES "users"("id")
);

-- Audit trail tab per incident
CREATE INDEX "audit_incident_created_idx" ON "incident_audit_logs" ("incident_id", "created_at");
-- Actor activity report (admin)
CREATE INDEX "audit_actor_created_idx"    ON "incident_audit_logs" ("actor_id", "created_at");
-- Filter by action type
CREATE INDEX "audit_action_idx"           ON "incident_audit_logs" ("action");
-- Time-range compliance queries
CREATE INDEX "audit_created_at_idx"       ON "incident_audit_logs" ("created_at");

-- =============================================================================
-- NOTIFICATIONS
-- =============================================================================

CREATE TABLE "notifications" (
  "id"           UUID               NOT NULL DEFAULT gen_random_uuid(),
  "user_id"      UUID               NOT NULL,
  "type"         "NotificationType" NOT NULL,
  "title"        TEXT               NOT NULL,
  "body"         TEXT               NOT NULL,
  -- reference_id: incidentId or other entity id for deep-linking
  "reference_id" UUID,
  "read"         BOOLEAN            NOT NULL DEFAULT FALSE,
  "read_at"      TIMESTAMPTZ,
  "created_at"   TIMESTAMPTZ        NOT NULL DEFAULT NOW(),

  CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"),
  -- read_at must only be set when read = true
  CONSTRAINT "notifications_read_at_consistency"
    CHECK ("read" = FALSE OR "read_at" IS NOT NULL),
  CONSTRAINT "fk_notifications_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- Unread badge count: SELECT COUNT(*) WHERE user_id = ? AND read = false
-- Composite index serves both badge count (with read = false filter) and the full inbox list
CREATE INDEX "notifications_user_read_idx"       ON "notifications" ("user_id", "read");
-- Notification inbox paginated list — newest first
CREATE INDEX "notifications_user_created_at_idx" ON "notifications" ("user_id", "created_at");

-- =============================================================================
-- NOTIFICATION PREFERENCES
-- =============================================================================

CREATE TABLE "notification_preferences" (
  "id"         UUID               NOT NULL DEFAULT gen_random_uuid(),
  "user_id"    UUID               NOT NULL,
  "type"       "NotificationType" NOT NULL,
  "in_app"     BOOLEAN            NOT NULL DEFAULT TRUE,
  "email"      BOOLEAN            NOT NULL DEFAULT FALSE,
  "created_at" TIMESTAMPTZ        NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ        NOT NULL DEFAULT NOW(),

  CONSTRAINT "notification_prefs_pkey"           PRIMARY KEY ("id"),
  -- One preference row per user per notification type
  CONSTRAINT "notification_prefs_user_type_unique" UNIQUE ("user_id", "type"),
  CONSTRAINT "fk_notif_prefs_user"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- Preference lookup before every notification dispatch
CREATE INDEX "notif_prefs_user_idx" ON "notification_preferences" ("user_id");
